name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_test:
  
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Instsll node modules
      run: npm instal
    - name: Execute static security tests
      run: npm audit
    - name: Execute inegration tests
      run: npm test

  deploy: 
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}


    
